### ISSUE TITLE
Crash on making a note on Windows

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#17]
When a note command is attempted, `manglersrv` crashes due to an out-of-bounds error.
```
panic: runtime error: slice bounds out of range

goroutine 6 [running]:
panic(0x55d860, 0xc08200a040)
        C:/Go/src/runtime/panic.go:481 +0x3f4
main.handle(0x275458, 0xc082024070)
        E:/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:111 +0x1527
main.main.func1(0x275380, 0xc082024070)
        E:/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:205 +0x282
created by main.main
        E:/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:206 +0xcd6
```
This line is the offender. ``strings.IndexRune(s, '\n')` returns `-1`. I took it as an invariant that lines end with a newline *somewhere*.
 ```go
			case 'n':
				// The note is all text after "n" and before the EOL, whitespace-trimmed.
				note := s[1:strings.IndexRune(s, '\n')]
```
Why is there no newline at the end of the line? There should be a linefeed after the carriage return on Windows.

**Comment by okitec** [comment]
This error happens because I used a Telnet client. Using netcat, it works. This is thus not Windows-specific nor is it a real bug. See also issue #16.
