### ISSUE TITLE
Out of memory in app's parser

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#37]
```
D/dalvikvm(12833): GC_FOR_ALLOC freed 1539K, 9% free 32000K/34951K, paused 76ms, total 76ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1525K, 9% free 32396K/35335K, paused 67ms, total 67ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1568K, 9% free 32800K/35783K, paused 67ms, total 67ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1550K, 9% free 33200K/36167K, paused 69ms, total 69ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1536K, 9% free 33595K/36551K, paused 70ms, total 70ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1522K, 8% free 33990K/36935K, paused 71ms, total 71ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1565K, 8% free 34393K/37383K, paused 72ms, total 72ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1547K, 8% free 34792K/37767K, paused 73ms, total 73ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1532K, 8% free 35188K/38151K, paused 73ms, total 73ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1490K, 8% free 35596K/38535K, paused 73ms, total 73ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1550K, 8% free 35998K/38983K, paused 74ms, total 74ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1535K, 8% free 36394K/39367K, paused 78ms, total 78ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1524K, 8% free 36786K/39751K, paused 76ms, total 76ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1513K, 8% free 37178K/40135K, paused 76ms, total 76ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1506K, 8% free 37566K/40519K, paused 78ms, total 78ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1500K, 8% free 37954K/40903K, paused 79ms, total 79ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1497K, 8% free 38338K/41287K, paused 80ms, total 80ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1490K, 8% free 38726K/41671K, paused 80ms, total 80ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1489K, 8% free 39108K/42055K, paused 85ms, total 85ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1486K, 7% free 39493K/42439K, paused 87ms, total 87ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1485K, 7% free 39874K/42823K, paused 82ms, total 82ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1482K, 7% free 40259K/43207K, paused 83ms, total 83ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1482K, 7% free 40641K/43591K, paused 85ms, total 85ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1482K, 7% free 41022K/43975K, paused 85ms, total 85ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1479K, 7% free 41407K/44359K, paused 86ms, total 86ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 41789K/44743K, paused 105ms, total 105ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 42170K/45127K, paused 97ms, total 97ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 42552K/45511K, paused 89ms, total 89ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 42933K/45895K, paused 90ms, total 90ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 43315K/46279K, paused 92ms, total 92ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 43696K/46663K, paused 95ms, total 95ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 44078K/47047K, paused 94ms, total 94ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 44459K/47431K, paused 93ms, total 93ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 44841K/47815K, paused 94ms, total 94ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 45222K/48199K, paused 96ms, total 96ms
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 45604K/48583K, paused 95ms, total 95ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.159MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 1478K, 7% free 45985K/48967K, paused 96ms, total 96ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.488MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 1289K, 6% free 46322K/49159K, paused 94ms, total 94ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.670MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 726K, 6% free 46509K/49159K, paused 93ms, total 93ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.782MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 439K, 6% free 46624K/49159K, paused 91ms, total 91ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.849MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 260K, 6% free 46693K/49159K, paused 89ms, total 89ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.888MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 154K, 5% free 46732K/49159K, paused 89ms, total 89ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.908MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 82K, 5% free 46752K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.918MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 41K, 5% free 46763K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.923MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 19K, 5% free 46769K/49159K, paused 90ms, total 90ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.925MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 11K, 5% free 46771K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.927MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 3K, 5% free 46772K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.927MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 3K, 5% free 46773K/49159K, paused 87ms, total 87ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.928MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed <1K, 5% free 46773K/49159K, paused 96ms, total 96ms
I/dalvikvm-heap(12833): Forcing collection of SoftReferences for 442-byte allocation
I/dalvikvm-heap(12833): Clamp target GC heap from 48.920MB to 48.000MB
D/dalvikvm(12833): GC_BEFORE_OOM freed 9K, 5% free 46764K/49159K, paused 100ms, total 100ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.929MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 34K, 5% free 46773K/49159K, paused 89ms, total 89ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.933MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 18K, 5% free 46777K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.935MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 7K, 5% free 46780K/49159K, paused 89ms, total 89ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.936MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 3K, 5% free 46781K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.937MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed 3K, 5% free 46781K/49159K, paused 88ms, total 88ms
I/dalvikvm-heap(12833): Clamp target GC heap from 48.937MB to 48.000MB
D/dalvikvm(12833): GC_FOR_ALLOC freed <1K, 5% free 46782K/49159K, paused 89ms, total 89ms
I/dalvikvm-heap(12833): Forcing collection of SoftReferences for 442-byte allocation
I/dalvikvm-heap(12833): Clamp target GC heap from 48.937MB to 48.000MB
D/dalvikvm(12833): GC_BEFORE_OOM freed 0K, 5% free 46782K/49159K, paused 98ms, total 98ms
E/dalvikvm-heap(12833): Out of memory on a 442-byte allocation.
I/dalvikvm(12833): "main" prio=5 tid=1 RUNNABLE JIT
I/dalvikvm(12833):   | group="main" sCount=0 dsCount=0 obj=0x41c2d508 self=0x41c1d470
I/dalvikvm(12833):   | sysTid=12833 nice=0 sched=0/0 cgrp=apps handle=1074790192
I/dalvikvm(12833):   | schedstat=( 11918925921 973007632 1888 ) utm=1170 stm=21 core=1
I/dalvikvm(12833):   at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:~94)
I/dalvikvm(12833):   at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
I/dalvikvm(12833):   at java.lang.StringBuilder.append(StringBuilder.java:216)
I/dalvikvm(12833):   at de.csgin.libmangler.Model$Parser.untok(Model.java:478)
I/dalvikvm(12833):   at de.csgin.libmangler.Model$Parser.sexprlist(Model.java:417)
I/dalvikvm(12833):   at de.csgin.libmangler.Model$Parser.sexprlist(Model.java:421)
I/dalvikvm(12833):   at de.csgin.libmangler.Model$Parser.sexpr(Model.java:392)
I/dalvikvm(12833):   at de.csgin.libmangler.Model$Parser.Parse(Model.java:385)
I/dalvikvm(12833):   at de.csgin.libmangler.Model.getBooks(Model.java:202)
I/dalvikvm(12833):   at de.csgin.libmangler.MainActivity.onCreate(MainActivity.java:100)
I/dalvikvm(12833):   at android.app.Activity.performCreate(Activity.java:5206)
I/dalvikvm(12833):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
I/dalvikvm(12833):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
I/dalvikvm(12833):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
I/dalvikvm(12833):   at android.app.ActivityThread.access$700(ActivityThread.java:140)
I/dalvikvm(12833):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
I/dalvikvm(12833):   at android.os.Handler.dispatchMessage(Handler.java:99)
I/dalvikvm(12833):   at android.os.Looper.loop(Looper.java:137)
I/dalvikvm(12833):   at android.app.ActivityThread.main(ActivityThread.java:4921)
I/dalvikvm(12833):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(12833):   at java.lang.reflect.Method.invoke(Method.java:511)
I/dalvikvm(12833):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
I/dalvikvm(12833):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
I/dalvikvm(12833):   at dalvik.system.NativeStart.main(Native Method)
```
@leletec What do I now? Optimise? What is that? Okay, maybe it's because of a bug.

**Comment by leletec** [comment]
That..looks bad.
Maybe to many running threads?

**Comment by okitec** [comment]
Runs all in the main thread. There is slight recursion, though, but it **should** be negligible (depth of recursion 3-4). Without the parser, the client can't understand the structure of the data the server sends, so it's not fatal, but displaying raw s-expressions is not the definition of user-friendly.

**Comment by leletec** [comment]
Do you know which method call times out / produces all the load?

**Comment by okitec** [comment]
Haven't yet profiled, but I guess (guessing is not a good idea when optimising) that it is all the new objects generated in my recursive methods.

https://github.com/okitec/libmangler/blob/master/client/src/de/csgin/libmangler/Model.java

**Comment by okitec** [comment]
Will be ignored. All functionality except pretty-printing works without this code.
