### ISSUE TITLE
Server crash in metadata select code

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#38]
Apparently, Go reflection is not working as I, a noob, expect.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4911d5]

goroutine 18 [running]:
panic(0x583620, 0xc82000a1a0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/okitec/libmangler/elem.glob.func4(0x0, 0x0, 0x0, 0xc8200f6140, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/oki/gowork/src/github.com/okitec/libmangler/elem/sel.go:200 +0x1195
github.com/okitec/libmangler/elem.Select(0xc800000043, 0x0, 0x0, 0x0, 0xc8200f6140, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/home/oki/gowork/src/github.com/okitec/libmangler/elem/sel.go:44 +0x223
main.interpret(0xc8200f6100, 0x3a, 0xc820045e70, 0x0, 0x0)
	/home/oki/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:115 +0x731
main.handle(0x7f5ee623a0d8, 0xc8200fc000)
	/home/oki/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:300 +0x17a
main.main.func2(0x7f5ee623a000, 0xc8200fc000)
	/home/oki/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:352 +0x27b
created by main.main
	/home/oki/gowork/src/github.com/okitec/libmangler/manglersrv/main.go:353 +0xb05
```

Offending lines, repeated in the B, C and U parts (all must be fixed!).
```go
// XXX crashes inevitably
if f.Type() == reflect.TypeOf((*User)(nil)) {
	if strings.Contains(f.Interface().(*User).Name, val) {
		rsel = append(rsel, c)
	}
} else if f.Type() == reflect.TypeOf((*Book)(nil)) {
	if strings.Contains(string(f.Interface().(*Book).ISBN), val) {
		rsel = append(rsel, c)
	}
}
```

**Comment by okitec** [comment]
The usig code in the client ha been edited to ignore this, so nopew, won't be fixed.
