### ISSUE TITLE
net.Listen failed with invalid argument on Windows

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#8]
On Windows 7 on a firewalled school computer, the networking code fails with an `ìnvalid argument` error:

```
H:\go-src\src\github.com\okitec\libmangler-master\manglersrv>manglersrv
2016/04/28 08:18:48 libmangler proto -1
2016/04/28 08:18:50 net.Listen failed: listen tcp :40000: socket: Ein ungültiges Argument wurde angegeben.
panic: net.Listen failed: listen tcp :40000: socket: Ein ungültiges Argument wurde angegeben.


goroutine 1 [running]:
panic(0x522100, 0xc082003bb0)
        H:/go/src/runtime/panic.go:464 +0x3f4
log.Panicln(0xc082063ee8, 0x2, 0x2)
        H:/go/src/log/log.go:334 +0xc8
main.main()
        H:/go-src/src/github.com/okitec/libmangler-master/manglersrv/main.go:126 +0x445
```

The code:

```
const (
	protoVersion = -1
	protoPort    = 40000
)
[...]
func main() {
[...]
	ln, err := net.Listen("tcp", fmt.Sprintf(":%d", protoPort))
```

**Comment by okitec** [comment]
Using `:20000` as the address leads to the same `invalid argument` error.
Using `localhost:20000` as the address leads to a `getaddrinfo` lookup error.
Using `127.0.0.1:20000` leads to a `invalid argument` error.

**Comment by okitec** [comment]
On a private Windows 10 computer, it doesn't crash on startup.

**Comment by okitec** [comment]
On my Windows 7 computer, it also doesn't crash on startup. The formatting bug is handled in #16 and the crash on making anote in #17.

**Comment by okitec** [comment]
The firewall of my school account seems totally broken. On different accounts in the same network, `manglersrv` works just fine.

**Comment by okitec** [comment]
Because it is not a bug I can fix, I'll just close it.
